name: Update Profile Repo

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Profile
        run: |
          # TODO: add your update commands here
          git add -A .
          git commit -m "generated"
          git push
          
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: plutoyty
          author_email: 2631223275@qq.com
          message: "Update profile repo"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}